### PR TITLE
fix: clear inactivity param when user logs in after inactivity (#594)

### LINKED ISSUE #594: Clear inactivity param when user logs in after inactivity
After inactivity, the route is updated with an inactivity parameter `inactivityTimeout`. This parameter needs to be removed when the user logs in again; currently the inactivity banner is rendered, after the user has logged in due to the authentication redirect after logging in.

### PR DESCRIPTION
**Pull request by frano-m**
Closes #594.

### CODE REVIEW

File: packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts [hunk 1]
```diff
@@ -34,7 +35,19 @@ export const useAuthenticationComplete = (
...
+
+/**
+ * Removes the inactivity timeout query parameter from the path.
+ * the inactivity timeout parameter is used to indicate that the session has timed out; remove the parameter to
+ * clear the session timeout banner after the user logs in again.
+ * @param path - Path.
+ * @returns path without the inactivity timeout query parameter.
+ */
+function removeInactivityTimeoutQueryParam(path: string): string {
+  const regex = new RegExp(`\\?${INACTIVITY_PARAM}.*`);
```
Comment (hunterckx) [inline packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts:49]: I wonder if it would work to use a `URLSearchParams` object (e.g. via a `URL` object) to modify the query params. The main benefit of this would be that if there were other query params for some reason, they would be left alone. (There might be other ways to accomplish this, but this is the only one that I know would be readily available.)

If we really expect the inactivity param to only appear alone, though, the only changes I would make would be to really make sure that only the param name we want gets matched, by using our `escapeRegExp` function and making sure there's something marking the end of the name:

```js
const regex = new RegExp(`\\?${escapeRegExp(INACTIVITY_PARAM)}(?:$|[=&].*)`);
```

(This will still match the entire query string when the inactivity param is present, it's just more precise about how it determines that the param is there)

Comment (frano-m) [reply packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts:49]: I think I went with the "clear anything after the inactivity param" to cover this weird use case:

- user is logged out and the url becomes `/path?inactivityTimeout=true`
- user updates the path with `/path?inactivityTimeout=true&catalog=my-catalog`
- user logs back in

I want to clear everything after `?inactivityTimeout` because the catalog will be in state and after logging back in the catalog will be added to the URL.

Thoughts?

Comment (hunterckx) [reply packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts:49]: Ah, okay. I don't know the details of how query parameters might be used in the app, so I was inclined to be cautious and just remove the one parameter; if we know it's okay to remove all of them, though, the alternative regex I suggested should work for that -- the only change I made was to make it match the parameter name more reliably, so that e.g. it will remove the entirety of `?inactivityTimeout=true&catalog=my-catalog` but will not affect `?inactivityTimeoutExample=true`

Comment (frano-m) [reply packages/data-explorer-ui/src/hooks/useAuthentication/useAuthenticationComplete.ts]: @hunterckx brilliant thank you! Done!

**Review by hunterckx — APPROVED** [review]
